export enum Elements {
  TABLE = 'DIV.header__table',
  HTML_VIEWER = 'DIV.html-viewer__content',
  INPUT = 'TEXTAREA.editor__input',
  BTN_SUBMIT = 'BUTTON.editor__button',
  STORY = 'P.story__text',
  BTN_NEXT = 'BUTTON.nav__button_next',
  BTN_PREV = 'BUTTON.nav__button_prev',
  BTN_HELP = 'BUTTON.aside__button_help',
  BTN_RESET = 'BUTTON.aside__button_reset',
  NAV_TITLE = 'H3.nav__title',
  NAV_BURGER = 'DIV.nav__burger',
  ASIDE_BURGER = 'DIV.aside-burger',
  HAND = 'DIV.header__hand-img',
  TASK = 'P.header__task',
  ASIDE_TITLE = 'H2.aside__title',
  ASIDE_CONTENT = 'P.aside__content',
}
